/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artiesten: Artiesten;
    inloggeschiedenis: Inloggeschiedeni;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artiesten: ArtiestenSelect<false> | ArtiestenSelect<true>;
    inloggeschiedenis: InloggeschiedenisSelect<false> | InloggeschiedenisSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-instellingen': SiteInstellingen;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-instellingen': SiteInstellingenSelect<false> | SiteInstellingenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Wie mag inloggen op dit paneel. Nieuwe aanmeldingen staan op 'in afwachting' en kunnen niets tot ze zijn goedgekeurd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Voor- en achternaam van deze gebruiker.
   */
  naam: string;
  /**
   * Zet op 'Goedgekeurd' om iemand toegang te geven; kies daarna de juiste rol.
   */
  status: 'in-afwachting' | 'goedgekeurd' | 'geweigerd' | 'geblokkeerd';
  /**
   * Beheerder kan alles beheren; redacteur past alleen teksten en foto's aan.
   */
  rol: 'eigenaar' | 'beheerder' | 'redacteur';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Alle foto's van de website. Upload hier nieuwe beelden en kies ze daarna in een pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Korte beschrijving van wat er op de foto staat. Wordt voorgelezen door schermlezers en getoond als de foto niet laadt.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * De makers achter ARTCHY. De volgorde bepaalt waar ze op de site staan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artiesten".
 */
export interface Artiesten {
  id: number;
  /**
   * Bijvoorbeeld "Josh". Wordt in hoofdletters getoond.
   */
  naam: string;
  /**
   * Kleine letters, geen spaties. Bepaalt de link naar de collectie, bijv. "josh" wordt /shop?type=josh.
   */
  slug: string;
  /**
   * De gouden regel onder de naam, bijvoorbeeld "The young visionary".
   */
  subtitel: string;
  /**
   * Eén à twee korte zinnen op de kaart. Houd het kort: langere teksten worden afgekapt.
   */
  tagline: string;
  /**
   * De tekst in het pop-upvenster. Gebruik Enter voor een nieuwe alinea.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Staand beeld. Aanbevolen formaat: 1200x1500px (verhouding 4:5), JPG.
   */
  portret?: (number | null) | Media;
  /**
   * Laag getal staat vooraan (1, 2, 3...).
   */
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Wie heeft wat gedaan, en wanneer. Deze lijst wordt automatisch bijgehouden en kan niet worden gewijzigd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inloggeschiedenis".
 */
export interface Inloggeschiedeni {
  id: number;
  tijdstip?: string | null;
  naam?: string | null;
  email?: string | null;
  actie?:
    | (
        | 'ingelogd'
        | 'uitgelogd'
        | 'inloggen-mislukt'
        | 'aangemaakt'
        | 'gewijzigd'
        | 'verwijderd'
        | 'gepubliceerd'
        | 'aanmelding-ontvangen'
        | 'goedgekeurd'
        | 'geweigerd'
        | 'geblokkeerd'
        | 'rol-gewijzigd'
      )
    | null;
  /**
   * Bijvoorbeeld "Homepage" of "Artiest: Brass".
   */
  onderdeel?: string | null;
  details?: string | null;
  ipAdres?: string | null;
  gebruiker?: (number | null) | User;
  verborgen?: boolean | null;
  resultaat?: ('gelukt' | 'mislukt') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'artiesten';
        value: number | Artiesten;
      } | null)
    | ({
        relationTo: 'inloggeschiedenis';
        value: number | Inloggeschiedeni;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  naam?: T;
  status?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artiesten_select".
 */
export interface ArtiestenSelect<T extends boolean = true> {
  naam?: T;
  slug?: T;
  subtitel?: T;
  tagline?: T;
  bio?: T;
  portret?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inloggeschiedenis_select".
 */
export interface InloggeschiedenisSelect<T extends boolean = true> {
  tijdstip?: T;
  naam?: T;
  email?: T;
  actie?: T;
  onderdeel?: T;
  details?: T;
  ipAdres?: T;
  gebruiker?: T;
  verborgen?: T;
  resultaat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Alles wat op de voorpagina staat. Wijzigingen zijn pas zichtbaar op de site nadat je op Publiceren klikt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  aankondiging?: {
    /**
     * Bijvoorbeeld "Limited drop".
     */
    accentTekst?: string | null;
    /**
     * Bijvoorbeeld "now live".
     */
    tekst?: string | null;
    /**
     * Bijvoorbeeld "Free shipping above €100".
     */
    tweedeTekst?: string | null;
  };
  hero?: {
    /**
     * Bijvoorbeeld "Wearable art platform".
     */
    eyebrow?: string | null;
    /**
     * De grote titel wordt per blok op een nieuwe regel gezet, bijv. WHERE / IMAGINATION / BECOMES IDENTITY.
     */
    titelRegels?:
      | {
          regel: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Bijvoorbeeld "Shop the drop".
     */
    knopTekst?: string | null;
    /**
     * Bijvoorbeeld "/shop".
     */
    knopLink?: string | null;
    /**
     * Aanbevolen formaat: 2300x630px, liggend. Laat leeg om de huidige foto van de site te blijven gebruiken.
     */
    afbeelding?: (number | null) | Media;
    /**
     * Aanbevolen formaat: 1000x1400px, staand. Laat leeg om de huidige foto van de site te blijven gebruiken.
     */
    afbeeldingMobiel?: (number | null) | Media;
  };
  /**
   * Bijvoorbeeld "Featured collections".
   */
  collectiesTitel?: string | null;
  /**
   * Drie kaarten geeft het mooiste beeld (één rij).
   */
  collecties?:
    | {
        titel: string;
        /**
         * Twee tot drie korte regels.
         */
        tagline?: string | null;
        /**
         * Bijvoorbeeld "/shop?type=josh".
         */
        link?: string | null;
        /**
         * Aanbevolen formaat: 1200x1200px, vierkant. Laat leeg om de huidige foto van de site te blijven gebruiken.
         */
        afbeelding?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  stappenTitel?: string | null;
  stappenSubtitel?: string | null;
  /**
   * Vier stappen passen precies op één rij.
   */
  stappen?:
    | {
        titel: string;
        tekst?: string | null;
        id?: string | null;
      }[]
    | null;
  dropEyebrow?: string | null;
  dropTitel?: string | null;
  dropSubregel?: string | null;
  /**
   * De klok telt af naar dit moment. Staat de datum in het verleden, dan toont de klok nullen.
   */
  dropEinddatum?: string | null;
  dropKnopTekst?: string | null;
  dropKnopLink?: string | null;
  /**
   * Aanbevolen formaat: 1000x1000px, vierkant. Laat leeg om de huidige foto van de site te blijven gebruiken.
   */
  dropAfbeelding?: (number | null) | Media;
  creatorsEyebrow?: string | null;
  creatorsTitel?: string | null;
  verhaalTitel?: string | null;
  /**
   * Eén alinea van ongeveer 4 tot 6 regels.
   */
  verhaalTekst?: string | null;
  /**
   * Aanbevolen formaat: 1600x900px, liggend. Laat leeg om de huidige foto van de site te blijven gebruiken.
   */
  verhaalAfbeelding?: (number | null) | Media;
  communityTitel?: string | null;
  communityTekst?: string | null;
  communityKnopTekst?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Het menu bovenaan, de footer en de social-links. Deze staan op elke pagina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-instellingen".
 */
export interface SiteInstellingen {
  id: number;
  /**
   * De links in de balk bovenaan. "Artists" heeft automatisch een uitklapmenu met de artiesten.
   */
  menu?:
    | {
        label: string;
        /**
         * Bijvoorbeeld "/shop".
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  merknaam?: string | null;
  merkOndertitel?: string | null;
  merkZin?: string | null;
  footerMenu?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  footerInfo?:
    | {
        label: string;
        /**
         * Laat leeg als er nog geen pagina is; de tekst wordt dan zonder link getoond.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  slogan?: string | null;
  /**
   * Laat een veld leeg om dat icoon te verbergen.
   */
  socials?: {
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  aankondiging?:
    | T
    | {
        accentTekst?: T;
        tekst?: T;
        tweedeTekst?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        titelRegels?:
          | T
          | {
              regel?: T;
              id?: T;
            };
        knopTekst?: T;
        knopLink?: T;
        afbeelding?: T;
        afbeeldingMobiel?: T;
      };
  collectiesTitel?: T;
  collecties?:
    | T
    | {
        titel?: T;
        tagline?: T;
        link?: T;
        afbeelding?: T;
        id?: T;
      };
  stappenTitel?: T;
  stappenSubtitel?: T;
  stappen?:
    | T
    | {
        titel?: T;
        tekst?: T;
        id?: T;
      };
  dropEyebrow?: T;
  dropTitel?: T;
  dropSubregel?: T;
  dropEinddatum?: T;
  dropKnopTekst?: T;
  dropKnopLink?: T;
  dropAfbeelding?: T;
  creatorsEyebrow?: T;
  creatorsTitel?: T;
  verhaalTitel?: T;
  verhaalTekst?: T;
  verhaalAfbeelding?: T;
  communityTitel?: T;
  communityTekst?: T;
  communityKnopTekst?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-instellingen_select".
 */
export interface SiteInstellingenSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  merknaam?: T;
  merkOndertitel?: T;
  merkZin?: T;
  footerMenu?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  footerInfo?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  slogan?: T;
  socials?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        youtube?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}