import { type MigrateDownArgs, type MigrateUpArgs, sql } from "@payloadcms/db-postgres";

/**
 * Nieuw global "Overige pagina's" (paginas): de teksten van /about en
 * /taji. Idempotent, geen versies/concepten — één rij met kolommen.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS public.paginas (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      over_titel character varying,
      over_tekst character varying,
      taji_eyebrow character varying,
      taji_titel character varying,
      taji_tekst character varying,
      taji_binnenkort character varying,
      taji_knop_tekst character varying,
      updated_at timestamp(3) with time zone,
      created_at timestamp(3) with time zone
    );
  `);
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`DROP TABLE IF EXISTS public.paginas;`);
}
