import { type MigrateDownArgs, type MigrateUpArgs, sql } from "@payloadcms/db-postgres";

/**
 * Eigen pagina per artiest, beheerd op het Artiesten-record:
 * - pagina-velden (eyebrow, kop, verhaal als rich text, binnenkort,
 *   knoptekst en -link) plus een beelden-tabel, incl. de
 *   versietabellen (Artiesten heeft concepten);
 * - de bestaande Taji-teksten verhuizen uit het oude tabblad
 *   "Overige pagina's → Taji" naar het Taji-record — niets gaat
 *   verloren — waarna de oude taji-kolommen verdwijnen;
 * - één nieuw veld voor de popup-knop naar de eigen pagina.
 *
 * Idempotent: opnieuw draaien kan geen kwaad.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE public.artiesten
      ADD COLUMN IF NOT EXISTS pagina_eyebrow character varying,
      ADD COLUMN IF NOT EXISTS pagina_kop character varying,
      ADD COLUMN IF NOT EXISTS pagina_tekst jsonb,
      ADD COLUMN IF NOT EXISTS pagina_binnenkort character varying,
      ADD COLUMN IF NOT EXISTS pagina_knop_tekst character varying,
      ADD COLUMN IF NOT EXISTS pagina_knop_link character varying;

    ALTER TABLE public._artiesten_v
      ADD COLUMN IF NOT EXISTS version_pagina_eyebrow character varying,
      ADD COLUMN IF NOT EXISTS version_pagina_kop character varying,
      ADD COLUMN IF NOT EXISTS version_pagina_tekst jsonb,
      ADD COLUMN IF NOT EXISTS version_pagina_binnenkort character varying,
      ADD COLUMN IF NOT EXISTS version_pagina_knop_tekst character varying,
      ADD COLUMN IF NOT EXISTS version_pagina_knop_link character varying;

    CREATE TABLE IF NOT EXISTS public.artiesten_pagina_beelden (
      _order integer NOT NULL,
      _parent_id integer NOT NULL,
      id character varying PRIMARY KEY,
      beeld_id integer
    );
    CREATE INDEX IF NOT EXISTS artiesten_pagina_beelden_order_idx
      ON public.artiesten_pagina_beelden USING btree (_order);
    CREATE INDEX IF NOT EXISTS artiesten_pagina_beelden_parent_id_idx
      ON public.artiesten_pagina_beelden USING btree (_parent_id);
    CREATE INDEX IF NOT EXISTS artiesten_pagina_beelden_beeld_idx
      ON public.artiesten_pagina_beelden USING btree (beeld_id);
    DO $$ BEGIN
      ALTER TABLE public.artiesten_pagina_beelden
        ADD CONSTRAINT artiesten_pagina_beelden_parent_id_fk
        FOREIGN KEY (_parent_id) REFERENCES public.artiesten(id) ON DELETE CASCADE;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    DO $$ BEGIN
      ALTER TABLE public.artiesten_pagina_beelden
        ADD CONSTRAINT artiesten_pagina_beelden_beeld_id_media_id_fk
        FOREIGN KEY (beeld_id) REFERENCES public.media(id) ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    CREATE TABLE IF NOT EXISTS public._artiesten_v_version_pagina_beelden (
      _order integer NOT NULL,
      _parent_id integer NOT NULL,
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      beeld_id integer,
      _uuid character varying
    );
    CREATE INDEX IF NOT EXISTS _artiesten_v_version_pagina_beelden_order_idx
      ON public._artiesten_v_version_pagina_beelden USING btree (_order);
    CREATE INDEX IF NOT EXISTS _artiesten_v_version_pagina_beelden_parent_id_idx
      ON public._artiesten_v_version_pagina_beelden USING btree (_parent_id);
    CREATE INDEX IF NOT EXISTS _artiesten_v_version_pagina_beelden_beeld_idx
      ON public._artiesten_v_version_pagina_beelden USING btree (beeld_id);
    DO $$ BEGIN
      ALTER TABLE public._artiesten_v_version_pagina_beelden
        ADD CONSTRAINT _artiesten_v_version_pagina_beelden_parent_id_fk
        FOREIGN KEY (_parent_id) REFERENCES public._artiesten_v(id) ON DELETE CASCADE;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    DO $$ BEGIN
      ALTER TABLE public._artiesten_v_version_pagina_beelden
        ADD CONSTRAINT _artiesten_v_version_pagina_beelden_beeld_id_media_id_fk
        FOREIGN KEY (beeld_id) REFERENCES public.media(id) ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    ALTER TABLE public.paginas
      ADD COLUMN IF NOT EXISTS artiesten_pagina_bio_pagina_knop_tekst character varying;
  `);

  // ---- Taji-teksten verhuizen (alleen als het oude tabblad bestaat
  //      en het Taji-record nog geen eigen pagina heeft) -------------
  const kolom = await db.execute(sql`
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'paginas'
       AND column_name = 'taji_titel'
  `);
  const heeftOudeTab = ((kolom as { rows?: unknown[] }).rows?.length ?? 0) > 0;

  if (heeftOudeTab) {
    const oud = (await db.execute(sql`
      SELECT taji_eyebrow, taji_titel, taji_tekst, taji_binnenkort,
             taji_knop_tekst
        FROM public.paginas LIMIT 1
    `)) as {
      rows?: Array<{
        taji_eyebrow?: string;
        taji_titel?: string;
        taji_tekst?: string;
        taji_binnenkort?: string;
        taji_knop_tekst?: string;
      }>;
    };
    const rij = oud.rows?.[0];

    if (rij?.taji_titel) {
      // Platte alinea's → het Lexical-formaat van de rich text-editor.
      const alineas = String(rij.taji_tekst ?? "")
        .split(/\n+/)
        .map((alinea) => alinea.trim())
        .filter(Boolean);
      const lexical = {
        root: {
          type: "root",
          format: "",
          indent: 0,
          version: 1,
          direction: "ltr",
          children: alineas.map((tekst) => ({
            type: "paragraph",
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                detail: 0,
                format: 0,
                mode: "normal",
                style: "",
                text: tekst,
                version: 1,
              },
            ],
          })),
        },
      };

      await db.execute(sql`
        UPDATE public.artiesten
           SET pagina_eyebrow = ${rij.taji_eyebrow ?? null},
               pagina_kop = ${rij.taji_titel ?? null},
               pagina_tekst = ${JSON.stringify(lexical)}::jsonb,
               pagina_binnenkort = ${rij.taji_binnenkort ?? null},
               pagina_knop_tekst = ${rij.taji_knop_tekst ?? null},
               pagina_knop_link = '/shop?type=taji'
         WHERE slug = 'taji' AND pagina_kop IS NULL
      `);
    }

    await db.execute(sql`
      ALTER TABLE public.paginas
        DROP COLUMN IF EXISTS taji_eyebrow,
        DROP COLUMN IF EXISTS taji_titel,
        DROP COLUMN IF EXISTS taji_tekst,
        DROP COLUMN IF EXISTS taji_binnenkort,
        DROP COLUMN IF EXISTS taji_knop_tekst;
    `);
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    DROP TABLE IF EXISTS public._artiesten_v_version_pagina_beelden;
    DROP TABLE IF EXISTS public.artiesten_pagina_beelden;
    ALTER TABLE public.artiesten
      DROP COLUMN IF EXISTS pagina_eyebrow,
      DROP COLUMN IF EXISTS pagina_kop,
      DROP COLUMN IF EXISTS pagina_tekst,
      DROP COLUMN IF EXISTS pagina_binnenkort,
      DROP COLUMN IF EXISTS pagina_knop_tekst,
      DROP COLUMN IF EXISTS pagina_knop_link;
  `);
}
